version: "3.9"
services:

  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - db-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
    image: julespi/usuarios
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: root
      CURSOS_URL: msvc-cursos:8002
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

volumes:
  db-mysql:
    name: db-mysql

networks:
  spring:
    name: spring

#### levantar todo con docker compose
# - docker-compose up -d

#### baja y elimina los contenedores
# - docker-compose down

#### levanta y construye todas las iamgenes de forma forzada
# - docker-compose up --build -d

#### solo construye todas las iamgenes de forma forzada
# - docker-compose build